"""
Density calculation from Stäckel potentials.

Poisson equation:

    ∇²Φ = 4πGρ

For ellipsoidal coordinates:

    ∇²Φ =
    1/(hλ hμ hν) *
    Σ_i ∂/∂q_i[(h_j h_k/h_i) ∂Φ/∂q_i]

where q_i=(λ,μ,ν).

Based on:
van de Ven et al. (2003)
"""

from __future__ import annotations

import numpy as np

from .geometry import EllipsoidalCoordinates
from .stackel import StackelPotential


class Density:
    """
    Density generated by a Stäckel potential.

    Parameters
    ----------
    coordinates:
        Ellipsoidal coordinate system.

    potential:
        Stäckel potential.

    G:
        Gravitational constant.
    """

    def __init__(self, coordinates: EllipsoidalCoordinates,
                 potential: StackelPotential, G: float = 1.0):
        self.coordinates = coordinates
        self.potential = potential
        self.G = G

    def _laplace_term(self, q, i, eps):
        """
        Calculate one coordinate contribution:

        ∂/∂q_i(A_i ∂Φ/∂q_i)

        """

        qp = np.array(q,dtype=float)
        qm = np.array(q,dtype=float)

        qp[i] += eps
        qm[i] -= eps

        hp = self.coordinates.scale_factors(*qp)
        hm = self.coordinates.scale_factors(*qm)

        dp = self.potential.derivatives(*qp)[i]
        dm = self.potential.derivatives(*qm)[i]

        if i == 0:
            Ap = hp[1]*hp[2]/hp[0]
            Am = hm[1]*hm[2]/hm[0]

        elif i == 1:
            Ap = hp[0]*hp[2]/hp[1]
            Am = hm[0]*hm[2]/hm[1]

        else:
            Ap = hp[0]*hp[1]/hp[2]
            Am = hm[0]*hm[1]/hm[2]

        return (Ap*dp-Am*dm)/(2*eps)


    def laplacian(self, lam, mu, nu, eps=1e-5):
        """
        Evaluate ∇²Φ.
        """

        q = (lam,mu,nu)

        h = self.coordinates.scale_factors(*q)

        numerator = sum(
            self._laplace_term(q,i,eps)
            for i in range(3)
        )

        return numerator/(h[0]*h[1]*h[2])


    def density(self, lam, mu, nu):
        """
        Return mass density:

            ρ = ∇²Φ/(4πG)
        """

        return self.laplacian(lam,mu,nu)/(4*np.pi*self.G)
